Ft css grids
ampaire/css-grids pull request #1
Opened 2019-10-10 14:01 UTC by Elijahscriptdev

Design your own Grid-based Framework Imitating the netflix page
![css-grids-ft-css-grids-index](https://user-images.githubusercontent.com/51033712/66575945-c412b100-eb6e-11e9-80c2-313818ed4795.png)

2019-10-10 18:13 UTC, whiz25 requested changes
## Good job guys :+1: 
Your clone looks nice. However, we need to work on the following requirements before we can merge.
- [ ] add classes to define columns size from 1/12th of a row to 100% of the row to the ```layout.css```
- [ ] add a ```.row``` class to your ```layout.css``` file
- [ ] add breakpoints like ```col-lg-1, col-sm-1, etc``` to the columns
- [ ] add and enable ```.stickler``` to this repo and make sure all checks pass
- [x] remove any comments from your code

### Make those changes and re-submit for another review.

2019-10-10 21:21 UTC, ampaire commented
@whiz25 , I have worked on the feedback. Could you please review? Thank you

2019-10-10 21:55 UTC, stratospherique requested changes
### Code Review by Ahmed Mahfoudh (TSE)

### Great work implementing the suggested changes :clap: . However, some changes needs to be made in regards to the responsiveness of your grid system. check below :arrow_down: 

#### Responsiveness

##### Breakpoints

* [ ] The CSS files should define a breakpoint for small screens with a width of up to 720px
  - For small screen sm
* [ ] The CSS files should define a breakpoint for medium screens with a width in the range of 720px - 1024px
  - For medium screens md
* [ ] The CSS files should define a breakpoint for large screens with width above 1024px
  - For large screens lg

- **[REQUIRED]** Fix The values for the media queries :pray: 

### That's it :relaxed: . When finished, kindly submit another code review form :pray:

2019-10-11 00:55 UTC, Redvanisation requested changes
### Hey team

### _Nice work implementing the changes so far, however, you still need to do the following before we move on:_

- [ ] The CSS files should define a breakpoint for large screens with width above 1024px

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

2019-10-11 00:55 UTC, Redvanisation commented on assets/layout.css
> +  }
Since you have this media query why did you define another one for `max-width: 1024px` just combine them because they do the same thing.

2019-10-11 07:15 UTC, wathigo approved these changes
## Hi Team :wave:   
**You can move on  :next_track_button:** 
_Good luck!_

2019-10-11 07:33 UTC, merged